### ISSUE TITLE
`falc proxy` silently fails if 5432 is already taken

### ISSUE THREAD

**Issue by seamusabshere** [faradayio/falconeri#4]
this is what success looks like:

```
$ falc proxy
Forwarding from [::1]:5432 -> 5432
Forwarding from 127.0.0.1:5432 -> 5432
```

this is what silent failure looks like (because a local postgres is running on 5432):

```
$ falc proxy
Forwarding from 127.0.0.1:5432 -> 5432
```

but

```
$ falc job list
Error: DatabaseError(__Unknown, "relation \"jobs\" does not exist")

could not list jobs
```

**Comment by emk** [comment]
Unfortunately, whatever is going on here is caused by `kubectl proxy`, which doesn't seem to have any options to customize its behavior.
